<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <title>XML Sitemap — VietnamDiving.com</title>
        <meta name="robots" content="noindex,follow"/>
        <style>
          :root { color-scheme: light; }
          * { box-sizing: border-box; }
          body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; color: #1a1a1a; background: #fafafa; }
          .wrap { max-width: 1100px; margin: 0 auto; padding: 40px 24px; }
          h1 { font-size: 28px; margin: 0 0 8px; letter-spacing: -0.01em; }
          .lede { color: #555; margin: 0 0 24px; font-size: 14px; line-height: 1.6; }
          .lede a { color: #c0392b; text-decoration: none; border-bottom: 1px solid currentColor; }
          .meta { color: #777; font-size: 12px; margin-bottom: 28px; }
          table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e6e6e6; border-radius: 6px; overflow: hidden; font-size: 14px; }
          th { text-align: left; background: #c0392b; color: #fff; font-weight: 600; padding: 12px 16px; font-size: 13px; letter-spacing: 0.02em; }
          td { padding: 10px 16px; border-top: 1px solid #f0f0f0; vertical-align: top; }
          tr:nth-child(even) td { background: #fbfbfb; }
          tr:hover td { background: #fff5f3; }
          a { color: #1a1a1a; text-decoration: none; }
          a:hover { color: #c0392b; text-decoration: underline; }
          .num { color: #999; width: 56px; }
          .small { color: #888; font-size: 12px; }
          .footer { margin-top: 28px; color: #888; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="wrap">
          <h1>XML Sitemap</h1>
          <p class="lede">Generated by <strong>VietnamDiving.com</strong> — this sitemap follows the same structure as Rank Math SEO. It is intended for search engines (Google, Bing, Yandex). For humans, visit <a href="/">vietnamdiving.com</a>.</p>

          <xsl:if test="sm:sitemapindex">
            <p class="meta">This is a <strong>sitemap index</strong> containing <xsl:value-of select="count(sm:sitemapindex/sm:sitemap)"/> sitemaps.</p>
            <table>
              <thead>
                <tr><th class="num">#</th><th>Sitemap URL</th><th>Last Modified</th></tr>
              </thead>
              <tbody>
                <xsl:for-each select="sm:sitemapindex/sm:sitemap">
                  <tr>
                    <td class="num"><xsl:value-of select="position()"/></td>
                    <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                    <td class="small"><xsl:value-of select="sm:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="sm:urlset">
            <p class="meta">This sitemap contains <xsl:value-of select="count(sm:urlset/sm:url)"/> URLs.</p>
            <table>
              <thead>
                <tr><th class="num">#</th><th>URL</th><th>Images</th><th>Priority</th><th>Change Freq.</th><th>Last Modified</th></tr>
              </thead>
              <tbody>
                <xsl:for-each select="sm:urlset/sm:url">
                  <tr>
                    <td class="num"><xsl:value-of select="position()"/></td>
                    <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                    <td class="small"><xsl:value-of select="count(image:image)"/></td>
                    <td class="small"><xsl:value-of select="sm:priority"/></td>
                    <td class="small"><xsl:value-of select="sm:changefreq"/></td>
                    <td class="small"><xsl:value-of select="sm:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <p class="footer">VietnamDiving.com — XML Sitemap (Rank Math style)</p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
