/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PageSitemapDotxmlRouteImport } from './routes/page-sitemap[.]xml'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GuideSitemapDotxmlRouteImport } from './routes/guide-sitemap[.]xml'
import { Route as DestinationSitemapDotxmlRouteImport } from './routes/destination-sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesPadiCoursesRouteImport } from './routes/guides.padi-courses'
import { Route as GuidesDiveMedicalRouteImport } from './routes/guides.dive-medical'
import { Route as GuidesBestTimeToDiveRouteImport } from './routes/guides.best-time-to-dive'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSitemapDotxmlRoute = PageSitemapDotxmlRouteImport.update({
  id: '/page-sitemap.xml',
  path: '/page-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSitemapDotxmlRoute = GuideSitemapDotxmlRouteImport.update({
  id: '/guide-sitemap.xml',
  path: '/guide-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationSitemapDotxmlRoute =
  DestinationSitemapDotxmlRouteImport.update({
    id: '/destination-sitemap.xml',
    path: '/destination-sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPadiCoursesRoute = GuidesPadiCoursesRouteImport.update({
  id: '/padi-courses',
  path: '/padi-courses',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesDiveMedicalRoute = GuidesDiveMedicalRouteImport.update({
  id: '/dive-medical',
  path: '/dive-medical',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesBestTimeToDiveRoute = GuidesBestTimeToDiveRouteImport.update({
  id: '/best-time-to-dive',
  path: '/best-time-to-dive',
  getParentRoute: () => GuidesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-sitemap.xml': typeof DestinationSitemapDotxmlRoute
  '/guide-sitemap.xml': typeof GuideSitemapDotxmlRoute
  '/guides': typeof GuidesRouteWithChildren
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/tours': typeof ToursRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/best-time-to-dive': typeof GuidesBestTimeToDiveRoute
  '/guides/dive-medical': typeof GuidesDiveMedicalRoute
  '/guides/padi-courses': typeof GuidesPadiCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-sitemap.xml': typeof DestinationSitemapDotxmlRoute
  '/guide-sitemap.xml': typeof GuideSitemapDotxmlRoute
  '/guides': typeof GuidesRouteWithChildren
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/tours': typeof ToursRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/best-time-to-dive': typeof GuidesBestTimeToDiveRoute
  '/guides/dive-medical': typeof GuidesDiveMedicalRoute
  '/guides/padi-courses': typeof GuidesPadiCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destination-sitemap.xml': typeof DestinationSitemapDotxmlRoute
  '/guide-sitemap.xml': typeof GuideSitemapDotxmlRoute
  '/guides': typeof GuidesRouteWithChildren
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/tours': typeof ToursRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/best-time-to-dive': typeof GuidesBestTimeToDiveRoute
  '/guides/dive-medical': typeof GuidesDiveMedicalRoute
  '/guides/padi-courses': typeof GuidesPadiCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/destination-sitemap.xml'
    | '/guide-sitemap.xml'
    | '/guides'
    | '/page-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/tours'
    | '/destinations/$slug'
    | '/guides/best-time-to-dive'
    | '/guides/dive-medical'
    | '/guides/padi-courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destination-sitemap.xml'
    | '/guide-sitemap.xml'
    | '/guides'
    | '/page-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/tours'
    | '/destinations/$slug'
    | '/guides/best-time-to-dive'
    | '/guides/dive-medical'
    | '/guides/padi-courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/destination-sitemap.xml'
    | '/guide-sitemap.xml'
    | '/guides'
    | '/page-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/tours'
    | '/destinations/$slug'
    | '/guides/best-time-to-dive'
    | '/guides/dive-medical'
    | '/guides/padi-courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationSitemapDotxmlRoute: typeof DestinationSitemapDotxmlRoute
  GuideSitemapDotxmlRoute: typeof GuideSitemapDotxmlRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  PageSitemapDotxmlRoute: typeof PageSitemapDotxmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  ToursRoute: typeof ToursRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-sitemap.xml': {
      id: '/page-sitemap.xml'
      path: '/page-sitemap.xml'
      fullPath: '/page-sitemap.xml'
      preLoaderRoute: typeof PageSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-sitemap.xml': {
      id: '/guide-sitemap.xml'
      path: '/guide-sitemap.xml'
      fullPath: '/guide-sitemap.xml'
      preLoaderRoute: typeof GuideSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-sitemap.xml': {
      id: '/destination-sitemap.xml'
      path: '/destination-sitemap.xml'
      fullPath: '/destination-sitemap.xml'
      preLoaderRoute: typeof DestinationSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/padi-courses': {
      id: '/guides/padi-courses'
      path: '/padi-courses'
      fullPath: '/guides/padi-courses'
      preLoaderRoute: typeof GuidesPadiCoursesRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/dive-medical': {
      id: '/guides/dive-medical'
      path: '/dive-medical'
      fullPath: '/guides/dive-medical'
      preLoaderRoute: typeof GuidesDiveMedicalRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/best-time-to-dive': {
      id: '/guides/best-time-to-dive'
      path: '/best-time-to-dive'
      fullPath: '/guides/best-time-to-dive'
      preLoaderRoute: typeof GuidesBestTimeToDiveRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesBestTimeToDiveRoute: typeof GuidesBestTimeToDiveRoute
  GuidesDiveMedicalRoute: typeof GuidesDiveMedicalRoute
  GuidesPadiCoursesRoute: typeof GuidesPadiCoursesRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesBestTimeToDiveRoute: GuidesBestTimeToDiveRoute,
  GuidesDiveMedicalRoute: GuidesDiveMedicalRoute,
  GuidesPadiCoursesRoute: GuidesPadiCoursesRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationSitemapDotxmlRoute: DestinationSitemapDotxmlRoute,
  GuideSitemapDotxmlRoute: GuideSitemapDotxmlRoute,
  GuidesRoute: GuidesRouteWithChildren,
  PageSitemapDotxmlRoute: PageSitemapDotxmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  ToursRoute: ToursRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
